name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Send email notification on success or failure
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build Notification - ${{ job.status }}
          body: |
            The build status is: ${{ job.status }}.
            Workflow: ${{ github.workflow }}.
            Repository: ${{ github.repository }}.
            Commit: ${{ github.sha }}.
          to: siddharthv4075.sv@gmail.com
          from: siddharthv4075.sv@gmail.com
